#!/bin/sh
# Assumes tmux sessions will have the same name as their projects root directories

if ! [ $PROJECTS_DIR ] # A folder in $HOME like "code" or "projects"
then
  PROJECTS_DIR=workspace # Default to workspace if environment variable isn't defined
fi

cd $HOME/$PROJECTS_DIR

if [ $1 ]
then
  if ! cd $1
  then
    echo "Invalid project directory."
    echo "$1"
    echo "Edit the file located at"
    whereis $0
    echo "and include the location of your projects directory"
    exit
  fi
else
   project=$(ls -d $HOME/$PROJECTS_DIR/*/ | grep -E -o "$PROJECTS_DIR\/.*" | grep -E -o '\/.*\/' | cut -d "/" -f 2 | pick)
  cd $project
fi

current_dir=${PWD##*/}

if ! tmux attach -t $current_dir
then
    echo "No tmux session exists for $current_dir. Creating now..."
    tmux new -s $current_dir
fi
