#!/bin/sh
# Assumes tmux sessions will have the same name as their projects
# and that those projects are all housed in a "projects" folder in the user's home folder

projects_dir=$HOME/workspace # path/to/projects/dir/here

cd $projects_dir

if [ $1 ]
then
  if ! cd $1
  then
    echo "Invalid project directory."
    echo "$1"
    echo "Edit the file located at"
    whereis $0
    echo "and include the location of your projects directory"
    exit
  fi
else
  project=$(ls -d */ | pick)
  cd $project
fi

current_dir=${PWD##*/}

if ! tmux attach -t $current_dir
then
    echo "No tmux session exists for $current_dir. Creating now..."
    tmux new -s $current_dir
fi
